- src: Stouts.apt
- src: Stouts.locale
- src: Stouts.timezone
- src: Stouts.users
- src: Stouts.nginx
- src: Stouts.redis
- name: Stouts.ruby
  src: 'https://github.com/khusnetdinov/Stouts.ruby.git'
- name: provision.other
  src: 'https://github.com/khusnetdinov/provision.other.git'
- src: ANXS.postgresql
- src: nickhammond.logrotate


