---
- hosts: all
  vars_files:
    - ../settings.yml
  remote_user: root
  roles:
    - role: locale
      locale_locales: "{{ deploy_locales }}"

    - role: timezone
      timezone_timezone: "{{ deploy_timezone }}"

    - role: swapfile
      swapfile_size: "{{ deploy_swapfile_size }}"
      swapfile_swappiness: 10

    - role: user
      user: "{{ deploy_user }}"
      home: "{{ deploy_user_home }}"

- hosts: all
  vars_files:
    - ../settings.yml
  become_user: deploy
  roles:
    - role: apt
      apt_upgrade: full
      apt_install_recommends: yes
      apt_install_packages: yes
      apt_packages: "{{ deploy_packages }}"

    - role: postgresql
      postgresql_version: "{{ deploy_postgres_version }}"
      postgresql_users:
        - name: "{{ deploy_postgres_user }}"
          pass: "{{ deploy_postgres_user }}"
      postgresql_databases:
        - name: "{{ deploy_postgres_database }}"
          owner: "{{ deploy_postgres_user }}"
          uuid_ossp: yes
      postgresql_user_privileges:
        - name: "{{ deploy_postgres_user }}"
          db: "{{ deploy_postgres_database }}"
          priv: "ALL"

    - role: redis
      redis_user: redis
      redis_bind: 127.0.0.1

    - role: nginx
      tags: [nginx]

    - role: logrotate
      logrotate_scripts:
        - name: "{{ deploy_project }}"
          path: "/var/www/{{ deploy_project }}/current/logs/*.log"
          options:
            - weekly
            - size 1M
            - compress
            - delaycompress
            - copytruncate

    - role: ruby
      rbenv_user: "{{ deploy_user }}"
      ruby_version: "{{ deploy_ruby_version }}"

    - role: folders
      deploy_user_group: "{{ deploy_user }}"
      project: "{{ deploy_project }}"
      folders: "{{ deploy_folders }}"

