---
- hosts: all
  sudo: yes
  roles:
    - role: apt
      apt_upgrade: full
      apt_install_recommends: yes
      apt_install_packages: yes
      apt_packages:
        - imagemagick

    - role: locale
      locale_locales:
      - ru_RU.UTF-8

    - role: timezone
      timezone_timezone: Europe/Moscow

    - role: users
      users_enaibled: yes
      users_groups:
        - name: sudo
          system: true
        - name: deploy
      users_users:
        - name: deploy
          system: true
          groups: sudo,deploy
      users_ssh_keys:
        - name: deploy
          authorized:
          - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      users_shell: /bin/zsh

    - role: other
      provision_user: deploy

- hosts: web
  sudo: yes
  roles:
    - role: nginx
      tags: [nginx]

    - role: ruby
      ruby_version: 2.2.2
      ruby_gems: [bundler]

- hosts: db
  sudo: yes
  roles:
    - role: postgresql
      postgresql_version: 9.5
      postgresql_encoding: 'UTF-8'
      postgresql_locale: 'en_US.UTF-8'
      postgresql_admin_user: "postgres"
      postgresql_default_auth_method: "trust"
      postgresql_cluster_name: "main"
      postgresql_cluster_reset: false
      postgresql_users:
        - name: techview
          pass: techview
      postgresql_databases:
        - name: techview_production
          owner: techview
          uuid_ossp: yes
      postgresql_user_privileges:
        - name: techview
          db: techview_production
          priv: "ALL"

    - role: redis
      redis_user: deploy
      redis_bind: 127.0.0.1

- hosts: service
  sudo: yes
  roles:
    - role: logrotate
      logrotate_scripts:
        - name: application
          path: '/var/log/applications/techview/*.log'
          options:
            - weekly
            - size 10M
            - compress
            - delaycompress
            - copytruncate
